package:
  name:    flexbox
  version: 0.0.1

source:
  git_rev: master
  git_url: https://github.com/cicwi/flexbox.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python >3.0
    - numpy >1.0
    - scikit-image >=0.13.0
    - scipy >=0.14
    - imageio
    - matplotlib

test:
  imports:
    -

about:
  home: https://github.com/cicwi/flexbox
  license:
  license_file:
